### ISSUE TITLE
Optimization Dialog Starts Off Center when New Trip from Main Menu

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#369]
If you start a new trip from the main menu or current trips, when the Optimization dialog appears, it is not in the center of the device window.

**Comment by aesculus** [comment]
Fixed in V1.2 (22).

**Comment by EVGrokker** [comment]
Still seeing the behavior in 1.2.0 (22).

**Comment by aesculus** [comment]
OK. I will need to get the iPhone later this week and try it there. Worked ok on the iPad.

**Comment by aesculus** [comment]
Lets try this again with V1.2 (23)

**Comment by EVGrokker** [comment]
v 1.2.0 (23)

The dialog is still shown in the lower right corner of the Plan screen.

**Comment by aesculus** [comment]
Yeah. I thought I fixed this. :-(

**Comment by EVGrokker** [comment]
It appears that you changed the design so that when planning a new trip initiated from the Plan screen, you switch to the map screen before displaying the New Trip dialog, which avoids the problem.

**Comment by EVGrokker** [comment]
v 1.2.0 (26)

It appears that if there are no current trips (a fresh install), creating a new trip switches to the Map screen before beginning the calculations, and the dialog is properly centered.

However, if there are current trips in existence, and a new trip is created from the Plan screen, the dialog appears in the lower right corner on a phone-sized device.

**Comment by aesculus** [comment]
> It appears that you changed the design so that when planning a new trip initiated from the Plan screen, you switch to the map screen before displaying the New Trip dialog, which avoids the problem.

It's always been this way. :-(

So far I cannot find a consistent way to have it screw up always. Seems random to me.

**Comment by aesculus** [comment]
I am having more luck getting it to screw up when I do a trip from the main panel vs the plan screen.  Did you mean the main panel?

**Comment by aesculus** [comment]
I made another attempt to force it to the center in V1.2 (27)

**Comment by EVGrokker** [comment]
v 1.2.0 (27)

1. With existing Current Trips, starting a New Trip from the Main screen opens the New Trip dialog. Upon touching Calculate, the screen switches to the Plan screen (good), but the dialog is still in the lower left corner.

2. Starting from a clean installation (after a Wipe), using Plan a Trip switches immediately to the Plan screen before opening the New Trip dialog. The dialog is properly centered.

3. Invoking New Trip from the Plan screen, the dialog is properly centered. 

The difference seems to be that when you switch to the Plan screen before opening the New Trip dialog (scenario 2 above), the dialog is properly displayed. When you wait to switch to the Plan screen until after the New Trip dialog is filled out (scenario 1 above) it fails.

**Comment by aesculus** [comment]
I'll try this sequence

**Comment by EVGrokker** [comment]
v 1.2.0 (33) still exhibits the behavior when planning a new trip from the Main screen.

**Comment by aesculus** [comment]
I remembered this after I published. Will try to address it today.

**Comment by aesculus** [comment]
I could not find a logical reason for this to do this. It may be a flaw in the framework.  I increased a delay I have set to way for the panel to switch that may help.  We'll have to see.

While I was in there I noticed I started the dialog in the wrong place when Auto was selected so I fixed that too in V1.2 (34).

**Comment by EVGrokker** [comment]
v 1.2.0 (44)

It's baaaaack!

**Comment by aesculus** [comment]
I never fixed it officially. I was going to attack it when we did the new dialog. Since we are keeping this one I need to fold all of this into the work about the auto recalc stuff.

**Comment by aesculus** [comment]
I am closing this because I have gone to a footer based status bar instead of a popup.
