### ISSUE TITLE
Initial Start Time Wrong in Return Trips Second Segment

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#428]
The trip start time is not being set correctly for a return trip on the return segment.  The date/time is the time the trip was created vs after the arrival time of the prior segment.

**Comment by aesculus** [comment]
I sort of fixed this in V1.2 (34) but it will report an date error on the Trip Summary until the user goes to the segment and it refreshes. This is related to issue #424 so once we have that figured out it should fix the error too.

**Comment by aesculus** [comment]
This has been fixed in V1.2 (37) again. It was using the first segments start times vs the first segments arrival time.

**Comment by EVGrokker** [comment]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (37) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Sand Dollar Inn & Cottages, [dt17jch7kcx5gb1d7rjn]

Not working correctly. 

My default departure time is set to 8am.

The outbound segment shows a proper departure of 8:00am, arriving 11:03am.

The return segment shows an incorrect departure time of 8:00am as well. At a minimum, it should be sometime after the arrival time of the first segment.

**Comment by aesculus** [comment]
I don't have this problem.  My second segment starts just after the first ends.

However I do have a problem that the status dialog is not appearing when I select the second segment from the Trip Browser nor does the Trip Browser get updated while still open.

**Comment by EVGrokker** [comment]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (38) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Sand Dollar Inn & Cottages, [j5ira8g81nswops3rg8h]

V 1.2.0 (38)
Still seeing a couple of problems with this round trip Seattle - Sand Dollar Inn, Moclips WA (1772):
- Departure time on second segment is the same as first segment, 8:00am 6/13.
- The segments traverse the same route, but segment one shows a departure SoC of 90%, with an arrival SoC of 27%, while the return segment shows a departure SoC of 90%, with an arrival SoC of -3%.

**Comment by EVGrokker** [comment]
Closing this as related to #463.
