### ISSUE TITLE
Downstream segment start date and times are not correct

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#97]
When creating a new segment, there are no rules for how the date/time are set. Right now it's the users' date/time which has no bearing at all.

What should the date/time be for new segments? Keep in mind that segments purposes can differ by use. In some cases it may be the next day and in some cases it may be another day or perhaps just flowing straight through being the previous segments destination arrival time.

When previous segment trip date/time is changed the downstream segments date/times are not updated automatically. This means all the additional calculations are not based on elapsed time for the trip.

This is an interesting dilemma in that some users may wish to manually set the other segments (like delaying a departure for a few days) and others might expect the dates/times to trickle down.

Not sure if this is a bug or an enhancement

**Comment by EVGrokker** [comment]
By default, I think that reasonable behavior would be that a new segment departs at the conclusion of the prior segment. We don't know what the user has in mind between segments. Maybe it's a meal stop, maybe it's an overnight stop, maybe it's several days visiting friends/relatives before continuing.

The tutorials should address planning a multi-segment trip, where one of the steps would be setting the desired departure dates and times for each leg. But obviously, that can change and require further  updates before the actual departure time.

If I change the departure time of segment two to tomorrow, then I would expect that all subsequent segments' departure times (segments 3 and later) would ripple accordingly. 

This means that if a user has previously established a departure offset of 12 hours between segments 2 and 3 (an overnight stay, for example), and they subsequently change the departure time of segment 2, that 12-hour buffer between segments 2 and 3 should be preserved during the ripple.

This issue generally gets into that gray area between Planning and Execution. EVTO is a planning app. To use it as the basis for real-time execution (navigation), you need to export your segment to either the in-car nav app via the calendar, or Google maps on the device (planned feature). 

For users who are only planning their trip with EVTO, and don't export to a navigation app, they're mostly interested in getting feedback about the project power consumption and planning their recharging. They're less likely to be concerned about last-minute recalculation.

Summary: new segments by default have a departure time corresponding to the arrival time of the previous segment. When user edits departure times, the buffer they've established between segments should be preserved.

**Comment by aesculus** [comment]
>If I change the departure time of segment two to tomorrow, then I would expect that all subsequent segments' departure times (segments 3 and later) would ripple accordingly.

Probably. Logic may be a bit hard to do but I am up for the challenge. :-)

**Comment by aesculus** [comment]
After thinking about this I think the problem deserves a popup whenever the Trip Date/Time changes. I think we should prompt the user for these choices:

1. Do nothing
2. Change only the dates on downstream segments if needed
3. Push out the time on all the downstream segments based on the time delta

**Comment by aesculus** [comment]
All downstream segments start times are now rippled from the prior segments arrival time (departure + trip time). Whenever the user goes to that segment after the date/time change the app will automatically update the weather if needed and recalculate the trip.  The trip (segment) will not be automatically re-optimized.

This behaves the same way if the user selects Refresh Segment from the menu.

Fixed in V1.2 (3)

**Comment by EVGrokker** [comment]
Awesome. I have a tutorial that will immediately benefit from this enhancement.

**Comment by aesculus** [comment]
Hopefully.

**Comment by EVGrokker** [comment]
I'll let you know. :)

**Comment by EVGrokker** [comment]
v 1.2 (3) … Not fixed.

Trip: Portland, [b5ko4nl9uumnf8l16l2scp]

I created a trip from Seattle WA to Lake Shasta CA, then segmented it at Portland OR and Medford OR.
I set the departure time for Segment 1 (Portland) to 8am 4/26/2017. Touching the Portland destination pin shows an arrival time of 11:06 am. So far so good.

Activate segment 2, Edit Segment Details. It shows a departure time of 7:59am on 4/26. Doc Brown would be delighted. 

Activate segment 3, Edit Segment Details. It shows a departure time of 8:04am on 4/26.  Hmm.

**Comment by aesculus** [comment]
Well I never tested for segmenting. Come on. :-)

**Comment by EVGrokker** [comment]
Uhm, what's the title of this issue? And who created it? :)

**Comment by aesculus** [comment]
It was for when you created a segment from Add Segment, not using those damn scissors.

Add Segment NOT Segmenting. :-)

**Comment by EVGrokker** [comment]
OHHHHH. I get it. The other kind of segments. 

You know what they say, don't let friends run with scissors! You might get stabbed.

**Comment by aesculus** [comment]
Well it worked out better in the end because it showed me another issue #325

**Comment by EVGrokker** [comment]
You're welcome. :)

**Comment by aesculus** [comment]
This was addressed in V1.2 (22).
